// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'703b359cbe2273ebac44a0381cb276672dba12e0a6a8e80dd7794c9fb85f1924'>;
export type ExecutionHash =
  ExecutionHashBase<'fa513b25a43eca91ae3fce99f39126091a9d2d77609eb87bcc4761279035458e'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly CategoryAssignment: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly ExamSession: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly userUuid: CodecTypes['pg/uuid@1']['output'];
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly isPassed: CodecTypes['pg/bool@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly completedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
    readonly ExamSessionQuestion: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly order: CodecTypes['pg/int4@1']['output'];
      readonly presentedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
    readonly Question: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly nr: CodecTypes['pg/int4@1']['output'];
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly answerA: CodecTypes['pg/text@1']['output'] | null;
      readonly answerB: CodecTypes['pg/text@1']['output'] | null;
      readonly answerC: CodecTypes['pg/text@1']['output'] | null;
      readonly correctAnswer: 'A' | 'B' | 'C' | 'T' | 'N';
      readonly media: CodecTypes['pg/text@1']['output'] | null;
      readonly level: 'PODSTAWOWY' | 'SPECJALISTYCZNY';
      readonly points: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly SavedQuestion: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly userUuid: CodecTypes['pg/uuid@1']['output'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly User: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly surname: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly role: 'USER' | 'ADMIN';
    };
    readonly UserAnswer: {
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly givenAnswer: 'A' | 'B' | 'C' | 'T' | 'N' | null;
      readonly isCorrect: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly CategoryAssignment: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly ExamSession: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly userUuid: CodecTypes['pg/uuid@1']['input'];
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly isPassed: CodecTypes['pg/bool@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly completedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
    readonly ExamSessionQuestion: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly order: CodecTypes['pg/int4@1']['input'];
      readonly presentedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
    readonly Question: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly nr: CodecTypes['pg/int4@1']['input'];
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly answerA: CodecTypes['pg/text@1']['input'] | null;
      readonly answerB: CodecTypes['pg/text@1']['input'] | null;
      readonly answerC: CodecTypes['pg/text@1']['input'] | null;
      readonly correctAnswer: 'A' | 'B' | 'C' | 'T' | 'N';
      readonly media: CodecTypes['pg/text@1']['input'] | null;
      readonly level: 'PODSTAWOWY' | 'SPECJALISTYCZNY';
      readonly points: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly SavedQuestion: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly userUuid: CodecTypes['pg/uuid@1']['input'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly User: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly surname: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly role: 'USER' | 'ADMIN';
    };
    readonly UserAnswer: {
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly givenAnswer: 'A' | 'B' | 'C' | 'T' | 'N' | null;
      readonly isCorrect: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categoryAssignment: {
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly examSession: {
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly completedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly isPassed: CodecTypes['pg/bool@1']['output'] | null;
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly userUuid: CodecTypes['pg/uuid@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly examSessionQuestion: {
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly order: CodecTypes['pg/int4@1']['output'];
      readonly presentedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly question: {
      readonly answerA: CodecTypes['pg/text@1']['output'] | null;
      readonly answerB: CodecTypes['pg/text@1']['output'] | null;
      readonly answerC: CodecTypes['pg/text@1']['output'] | null;
      readonly content: CodecTypes['pg/text@1']['output'];
      readonly correctAnswer: 'A' | 'B' | 'C' | 'T' | 'N';
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly level: 'PODSTAWOWY' | 'SPECJALISTYCZNY';
      readonly media: CodecTypes['pg/text@1']['output'] | null;
      readonly nr: CodecTypes['pg/int4@1']['output'];
      readonly points: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly savedQuestion: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly userUuid: CodecTypes['pg/uuid@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly role: 'USER' | 'ADMIN';
      readonly surname: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
    readonly userAnswer: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly givenAnswer: 'A' | 'B' | 'C' | 'T' | 'N' | null;
      readonly isCorrect: CodecTypes['pg/bool@1']['output'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['output'];
      readonly uuid: CodecTypes['pg/uuid@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categoryAssignment: {
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly examSession: {
      readonly category:
        | 'AM'
        | 'A1'
        | 'A2'
        | 'A'
        | 'B1'
        | 'B'
        | 'B+E'
        | 'C'
        | 'C1'
        | 'C1+E'
        | 'C+E'
        | 'D'
        | 'D1'
        | 'D1+E'
        | 'D+E'
        | 'T'
        | 'PT';
      readonly completedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly isPassed: CodecTypes['pg/bool@1']['input'] | null;
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly userUuid: CodecTypes['pg/uuid@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly examSessionQuestion: {
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly order: CodecTypes['pg/int4@1']['input'];
      readonly presentedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly question: {
      readonly answerA: CodecTypes['pg/text@1']['input'] | null;
      readonly answerB: CodecTypes['pg/text@1']['input'] | null;
      readonly answerC: CodecTypes['pg/text@1']['input'] | null;
      readonly content: CodecTypes['pg/text@1']['input'];
      readonly correctAnswer: 'A' | 'B' | 'C' | 'T' | 'N';
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly level: 'PODSTAWOWY' | 'SPECJALISTYCZNY';
      readonly media: CodecTypes['pg/text@1']['input'] | null;
      readonly nr: CodecTypes['pg/int4@1']['input'];
      readonly points: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly savedQuestion: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly userUuid: CodecTypes['pg/uuid@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly user: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly role: 'USER' | 'ADMIN';
      readonly surname: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
    readonly userAnswer: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly examSessionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly givenAnswer: 'A' | 'B' | 'C' | 'T' | 'N' | null;
      readonly isCorrect: CodecTypes['pg/bool@1']['input'];
      readonly questionUuid: CodecTypes['pg/uuid@1']['input'];
      readonly uuid: CodecTypes['pg/uuid@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categoryAssignment: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly questionUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'categoryAssignment_questionUuid_idx_88476262';
                  readonly prefix: 'categoryAssignment_questionUuid_idx';
                  readonly columns: readonly ['questionUuid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categoryAssignment';
                    readonly columns: readonly ['questionUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'question';
                    readonly columns: readonly ['uuid'];
                  };
                },
              ];
            };
            readonly examSession: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly userUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly isPassed: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly completedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'examSession_userUuid_idx_d8ac540b';
                  readonly prefix: 'examSession_userUuid_idx';
                  readonly columns: readonly ['userUuid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'examSession';
                    readonly columns: readonly ['userUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['uuid'];
                  };
                },
              ];
            };
            readonly examSessionQuestion: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly examSessionUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly questionUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly order: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly presentedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [
                { readonly columns: readonly ['examSessionUuid', 'questionUuid'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'examSessionQuestion_examSessionUuid_idx_39147978';
                  readonly prefix: 'examSessionQuestion_examSessionUuid_idx';
                  readonly columns: readonly ['examSessionUuid'];
                  readonly unique: false;
                },
                {
                  readonly name: 'examSessionQuestion_questionUuid_idx_88476262';
                  readonly prefix: 'examSessionQuestion_questionUuid_idx';
                  readonly columns: readonly ['questionUuid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'examSessionQuestion';
                    readonly columns: readonly ['examSessionUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'examSession';
                    readonly columns: readonly ['uuid'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'examSessionQuestion';
                    readonly columns: readonly ['questionUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'question';
                    readonly columns: readonly ['uuid'];
                  };
                },
              ];
            };
            readonly question: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nr: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly content: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly answerA: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly answerB: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly answerC: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly correctAnswer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly media: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly level: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly points: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly savedQuestion: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly userUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly questionUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [{ readonly columns: readonly ['userUuid', 'questionUuid'] }];
              indexes: readonly [
                {
                  readonly name: 'savedQuestion_userUuid_idx_d8ac540b';
                  readonly prefix: 'savedQuestion_userUuid_idx';
                  readonly columns: readonly ['userUuid'];
                  readonly unique: false;
                },
                {
                  readonly name: 'savedQuestion_questionUuid_idx_88476262';
                  readonly prefix: 'savedQuestion_questionUuid_idx';
                  readonly columns: readonly ['questionUuid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'savedQuestion';
                    readonly columns: readonly ['userUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['uuid'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'savedQuestion';
                    readonly columns: readonly ['questionUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'question';
                    readonly columns: readonly ['uuid'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly surname: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'USER'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly userAnswer: {
              columns: {
                readonly uuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly examSessionUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly questionUuid: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly givenAnswer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly isCorrect: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['uuid'] };
              uniques: readonly [
                { readonly columns: readonly ['examSessionUuid', 'questionUuid'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'userAnswer_examSessionUuid_idx_39147978';
                  readonly prefix: 'userAnswer_examSessionUuid_idx';
                  readonly columns: readonly ['examSessionUuid'];
                  readonly unique: false;
                },
                {
                  readonly name: 'userAnswer_questionUuid_idx_88476262';
                  readonly prefix: 'userAnswer_questionUuid_idx';
                  readonly columns: readonly ['questionUuid'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'userAnswer';
                    readonly columns: readonly ['examSessionUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'examSession';
                    readonly columns: readonly ['uuid'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'userAnswer';
                    readonly columns: readonly ['questionUuid'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'question';
                    readonly columns: readonly ['uuid'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly Answer: {
              readonly kind: 'valueSet';
              readonly values: readonly ['A', 'B', 'C', 'T', 'N'];
            };
            readonly Category: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'AM',
                'A1',
                'A2',
                'A',
                'B1',
                'B',
                'B+E',
                'C',
                'C1',
                'C1+E',
                'C+E',
                'D',
                'D1',
                'D1+E',
                'D+E',
                'T',
                'PT',
              ];
            };
            readonly Level: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PODSTAWOWY', 'SPECJALISTYCZNY'];
            };
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['USER', 'ADMIN'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly question: { readonly namespace: 'public' & NamespaceId; readonly model: 'Question' };
    readonly categoryAssignment: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CategoryAssignment';
    };
    readonly examSession: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ExamSession';
    };
    readonly examSessionQuestion: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ExamSessionQuestion';
    };
    readonly userAnswer: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserAnswer';
    };
    readonly savedQuestion: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SavedQuestion';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly CategoryAssignment: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly questionUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['questionUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categoryAssignment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly category: { readonly column: 'category' };
                readonly questionUuid: { readonly column: 'questionUuid' };
              };
            };
          };
          readonly ExamSession: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly score: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isPassed: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly completedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly answers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserAnswer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['examSessionUuid'];
                };
              };
              readonly questions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExamSessionQuestion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['examSessionUuid'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'examSession';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly userUuid: { readonly column: 'userUuid' };
                readonly category: { readonly column: 'category' };
                readonly score: { readonly column: 'score' };
                readonly isPassed: { readonly column: 'isPassed' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly completedAt: { readonly column: 'completedAt' };
              };
            };
          };
          readonly ExamSessionQuestion: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly examSessionUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly questionUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly order: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly presentedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly examSession: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExamSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['examSessionUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['questionUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'examSessionQuestion';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly examSessionUuid: { readonly column: 'examSessionUuid' };
                readonly questionUuid: { readonly column: 'questionUuid' };
                readonly order: { readonly column: 'order' };
                readonly presentedAt: { readonly column: 'presentedAt' };
              };
            };
          };
          readonly Question: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nr: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly content: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly answerA: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly answerB: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly answerC: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly correctAnswer: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly media: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly level: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly points: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly categories: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'CategoryAssignment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['questionUuid'];
                };
              };
              readonly examSessionQuestions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExamSessionQuestion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['questionUuid'];
                };
              };
              readonly savedQuestions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SavedQuestion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['questionUuid'];
                };
              };
              readonly userAnswers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'UserAnswer';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['questionUuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'question';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly nr: { readonly column: 'nr' };
                readonly content: { readonly column: 'content' };
                readonly answerA: { readonly column: 'answerA' };
                readonly answerB: { readonly column: 'answerB' };
                readonly answerC: { readonly column: 'answerC' };
                readonly correctAnswer: { readonly column: 'correctAnswer' };
                readonly media: { readonly column: 'media' };
                readonly level: { readonly column: 'level' };
                readonly points: { readonly column: 'points' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly SavedQuestion: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly questionUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['questionUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
              readonly user: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'savedQuestion';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly userUuid: { readonly column: 'userUuid' };
                readonly questionUuid: { readonly column: 'questionUuid' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly surname: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly examSessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExamSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['userUuid'];
                };
              };
              readonly savedQuestions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SavedQuestion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['uuid'];
                  readonly targetFields: readonly ['userUuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly email: { readonly column: 'email' };
                readonly name: { readonly column: 'name' };
                readonly surname: { readonly column: 'surname' };
                readonly password: { readonly column: 'password' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly isActive: { readonly column: 'isActive' };
                readonly role: { readonly column: 'role' };
              };
            };
          };
          readonly UserAnswer: {
            readonly fields: {
              readonly uuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly examSessionUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly questionUuid: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly givenAnswer: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isCorrect: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly examSession: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ExamSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['examSessionUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['questionUuid'];
                  readonly targetFields: readonly ['uuid'];
                };
              };
            };
            readonly storage: {
              readonly table: 'userAnswer';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly uuid: { readonly column: 'uuid' };
                readonly examSessionUuid: { readonly column: 'examSessionUuid' };
                readonly questionUuid: { readonly column: 'questionUuid' };
                readonly givenAnswer: { readonly column: 'givenAnswer' };
                readonly isCorrect: { readonly column: 'isCorrect' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly Level: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PODSTAWOWY'; readonly value: 'PODSTAWOWY' },
              { readonly name: 'SPECJALISTYCZNY'; readonly value: 'SPECJALISTYCZNY' },
            ];
          };
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'USER'; readonly value: 'USER' },
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
            ];
          };
          readonly Category: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AM'; readonly value: 'AM' },
              { readonly name: 'A1'; readonly value: 'A1' },
              { readonly name: 'A2'; readonly value: 'A2' },
              { readonly name: 'A'; readonly value: 'A' },
              { readonly name: 'B1'; readonly value: 'B1' },
              { readonly name: 'B'; readonly value: 'B' },
              { readonly name: 'B_E'; readonly value: 'B+E' },
              { readonly name: 'C'; readonly value: 'C' },
              { readonly name: 'C1'; readonly value: 'C1' },
              { readonly name: 'C1_E'; readonly value: 'C1+E' },
              { readonly name: 'C_E'; readonly value: 'C+E' },
              { readonly name: 'D'; readonly value: 'D' },
              { readonly name: 'D1'; readonly value: 'D1' },
              { readonly name: 'D1_E'; readonly value: 'D1+E' },
              { readonly name: 'D_E'; readonly value: 'D+E' },
              { readonly name: 'T'; readonly value: 'T' },
              { readonly name: 'PT'; readonly value: 'PT' },
            ];
          };
          readonly Answer: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'A'; readonly value: 'A' },
              { readonly name: 'B'; readonly value: 'B' },
              { readonly name: 'C'; readonly value: 'C' },
              { readonly name: 'T'; readonly value: 'T' },
              { readonly name: 'N'; readonly value: 'N' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'categoryAssignment';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'examSession';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'examSessionQuestion';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'question';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'question';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'savedQuestion';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'user';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'userAnswer';
            readonly column: 'uuid';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
